url: "https://starshrimp.github.io" # The base hostname & protocol for your site
baseurl: "/wernermeyerconsulting" # The subpath of your site, e.g. /blog


# Site settings
title: W. Meyer Consulting
email: wm@wmeyerconsulting.ch
description: "Specializing in succession planning and asset protection, W. Meyer Consulting offers tailored strategies for international families and high-net-worth individuals."



# Postal address (add as many lines as necessary)
address:
  - line: Rainstrasse 7
  - line: 8907 Wettswil

# Build settings
markdown: kramdown
permalink: pretty